version: "3"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - jhacks-judge-db-volume:/var/lib/mysql
volumes:
  jhacks-judge-db-volume: