version: "3"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - jhacks-judge-db-volume:/var/lib/mysql
  nginx:
    restart: "always"
    image: "nginx:latest"
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "9001:9001"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "1337:1337"
volumes:
  jhacks-judge-db-volume: